# Start from a base image with Ubuntu
FROM ubuntu:jammy

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go-gtids-linux binary from current directory to the working directory in container
# and rename it to go-gtids
COPY go-gtids-linux ./go-gtids


# Copy .my.cnf to /root/.my.cnf and set permissions
COPY .my.cnf-FLYWAY /root/.my.cnf
RUN chmod 600 /root/.my.cnf

# This container will run go-gtids by default
ENTRYPOINT ["./go-gtids"]