# Start from a base image with Ubuntu
FROM ubuntu:jammy

# Set the Current Working Directory inside the container
WORKDIR /app


RUN apt-get update && \
    apt-get install -y percona-toolkit mysql-client strace vim && \
    rm -rf /var/lib/apt/lists/*

# Copy .my.cnf to /root/.my.cnf and set permissions
COPY .my.cnf-FLYWAY /root/.my.cnf
RUN chmod 600 /root/.my.cnf

# This container will run pt-slave-restart by default
ENTRYPOINT ["pt-slave-restart"]